
package mp3Player;

import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

public class mp3PlayerGUI extends javax.swing.JDialog {

    MainClass mc=new MainClass();
    
    int xmouse;
    int ymouse;
    
    int xx;
    int xy;
    
    public static int count;
    
    int width=(Toolkit.getDefaultToolkit().getScreenSize().width/2)-185;
    int height=(Toolkit.getDefaultToolkit().getScreenSize().height-180);
    
    public mp3PlayerGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocation(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLDisplay = new javax.swing.JLabel();
        jLplay = new javax.swing.JLabel();
        jLstop = new javax.swing.JLabel();
        jLpause = new javax.swing.JLabel();
        jLplaylist = new javax.swing.JLabel();
        jLloop = new javax.swing.JLabel();
        jLLoopstatus = new javax.swing.JLabel();
        jLbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLDisplay.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jLDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLDisplayMouseReleased(evt);
            }
        });
        jPanel1.add(jLDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 340, 20));

        jLplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLplayMouseReleased(evt);
            }
        });
        jPanel1.add(jLplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, 50));

        jLstop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLstopMouseReleased(evt);
            }
        });
        jPanel1.add(jLstop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 20, 20));

        jLpause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLpauseMouseReleased(evt);
            }
        });
        jPanel1.add(jLpause, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 30, 20));

        jLplaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLplaylistMouseReleased(evt);
            }
        });
        jPanel1.add(jLplaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 75, 40, 20));

        jLloop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLloopMouseReleased(evt);
            }
        });
        jPanel1.add(jLloop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 30, 30));

        jLLoopstatus.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        jLLoopstatus.setForeground(new java.awt.Color(51, 255, 0));
        jPanel1.add(jLLoopstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 20));

        jLbackground.setIcon(new javax.swing.ImageIcon("F:\\ANJANA\\MY PROJECTS\\Netbeans\\MusicPlayer\\src\\mp3Player\\mplayer.jpg")); // NOI18N
        jLbackground.setText("jLabel1");
        jLbackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLbackgroundMouseDragged(evt);
            }
        });
        jLbackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbackgroundMousePressed(evt);
            }
        });
        jPanel1.add(jLbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLstopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLstopMouseReleased
        mc.stop();
    }//GEN-LAST:event_jLstopMouseReleased

    private void jLplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLplayMouseReleased
        //mc.play("E:\\Songs\\Awanhale Susum Hela-Unplugged__Mariyans_mp3[www.sarigama.lk].mp3");
        mc.resume();
    }//GEN-LAST:event_jLplayMouseReleased

    private void jLpauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpauseMouseReleased
        mc.pause();
    }//GEN-LAST:event_jLpauseMouseReleased

    private void jLplaylistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLplaylistMouseReleased
        FileFilter filter=new FileNameExtensionFilter("MP3 Files","mp3","mpeg3");
        
        JFileChooser chooser=new JFileChooser("E:\\Songs");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal=chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            mc.stop();
            File myFile=chooser.getSelectedFile();
            String song=myFile + "";
            
            String name= chooser.getSelectedFile().getName();
            jLDisplay.setText(name);
            
            mc.play(song);
        }
    }//GEN-LAST:event_jLplaylistMouseReleased

    private void jLDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLDisplayMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLDisplayMouseReleased

    private void jLloopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLloopMouseReleased
        switch(count)
        {
            case 0:
                count =1;
                //System.out.println(count);
                jLLoopstatus.setText("Loop On");
                break;
                
            case 1:
                count =0;
                //System.out.println(count);
                jLLoopstatus.setText("Loop Off");
                break;
        }
    }//GEN-LAST:event_jLloopMouseReleased

    private void jLbackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbackgroundMousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_jLbackgroundMousePressed

    private void jLbackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbackgroundMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLbackgroundMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mp3PlayerGUI dialog = new mp3PlayerGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLDisplay;
    private javax.swing.JLabel jLLoopstatus;
    private javax.swing.JLabel jLbackground;
    private javax.swing.JLabel jLloop;
    private javax.swing.JLabel jLpause;
    private javax.swing.JLabel jLplay;
    private javax.swing.JLabel jLplaylist;
    private javax.swing.JLabel jLstop;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
